### ISSUE TITLE
error using pip install 

### ISSUE THREAD

**Issue by beebek** [chrisglass/xhtml2pdf#128]
I am using virutal environment in windows7. while installing using pip it gives error.

but using easy_install gives no error. 
http://pastebin.com/Wm8mnwLt

But using easy_install is fine though. Since all my requirements are in requirements.txt file just wanted to include its requirement too.

**Comment by mrts** [comment]
The error is not related to xhtml2pdf, but to PIL. Using wheels works fine in Windows 7, try with

    pip install --use-wheel --requirement=requirements.txt

Ticket can be closed as it works for me.
